@host = http://localhost:3000

### init signing action
POST {{host}}/auth/action/init
Content-Type: application/json

{
  "userActionPayload": "{ \"kind\": \"EndUser\", \"email\": \"test@test.test\" }",
  "userActionHttpMethod": "POST",
  "userActionHttpPath": "/auth/registration/delegated",
  "userActionServerKind": "Api"
}

### init registration

POST {{host}}/auth/register/init
Content-Type: application/json

{
  "username": "test@test.test"
}