@host = http://localhost:4242

### Get all networks
GET {{host}}/networks

###

### Get Ethereum network by ID
GET {{host}}/networks/ethereum

###

### Get Polygon network by ID
GET {{host}}/networks/polygon

###

### Test network not found (should return 404)
GET {{host}}/networks/invalid-network

###

